### ISSUE TITLE
The icon seems to be wrong

### ISSUE THREAD

**Issue by sinetek** [ivan-hc/Steam-appimage#27] opened 2024-09-05 18:01 UTC
I don't know if this is just my setup, but the appimage icon does not seem to show up correctly in Dolphin:

![image](https://github.com/user-attachments/assets/0609ec39-94bd-4a98-b1e8-3a84713f7d28)

**Comment by ivan-hc** [comment] 2024-09-05 19:34
First of all we should know how Dolphin detects the "right" icon, my AppImage only contain 4 files and a symlink to the icon

![Istantanea_2024-09-05_21-33-58](https://github.com/user-attachments/assets/93e5c75b-79df-4af7-906c-fdf8d165bf22)

**Comment by sinetek** [comment] 2024-09-05 19:59
Howdy Ivan 👋

![steam no icon2](https://github.com/user-attachments/assets/23a57cd6-27f3-4df3-810e-e3c33916b51c)

seems to happen also with Nemo

**Comment by ivan-hc** [comment] 2024-09-05 20:03
uhm.... just curious, try to download other random appimages from my repositories https://github.com/ivan-hc#my-appimage-packages I have the suspect that its due to newer compression via appimagetool (my AppImages does not require libfuse2)

**Comment by ivan-hc** [comment] 2024-09-05 20:23
also test with these appimages by @Samueru-sama
- https://github.com/Samueru-sama/mpv-AppImage
- https://github.com/Samueru-sama/android-tools-AppImage
- https://github.com/Samueru-sama/DeaDBeeF-AppImage

we bundle appimages using the same appimagetool from https://github.com/AppImage/appimagetool

**Comment by Samueru-sama** [comment] 2024-09-05 21:04
I have the xapp appimage thumbnailer with thunar and I have no problem seeing the Steam appimage icon; 

![image](https://github.com/user-attachments/assets/1b68f838-3cca-4df4-b0e2-e893fe85a7ff)

**Comment by sinetek** [comment] 2024-09-06 11:05
> also test with these appimages by @Samueru-sama
> 
> * https://github.com/Samueru-sama/mpv-AppImage
> * https://github.com/Samueru-sama/android-tools-AppImage
> * https://github.com/Samueru-sama/DeaDBeeF-AppImage
> 
> we bundle appimages using the same appimagetool from https://github.com/AppImage/appimagetool

None of these show up with an icon file. Maybe it could be fixed with a more recent (how recent?) version of software, but the point of AppImages is to support applications on any distribution release, so it would be nice to have these working.

My OS is Gentoo (stable profile desktop) with the newly released stable KDE6 packages.

**Comment by Samueru-sama** [comment] 2024-09-06 11:10
> > also test with these appimages by @Samueru-sama
> > 
> > * https://github.com/Samueru-sama/mpv-AppImage
> > * https://github.com/Samueru-sama/android-tools-AppImage
> > * https://github.com/Samueru-sama/DeaDBeeF-AppImage
> > 
> > we bundle appimages using the same appimagetool from https://github.com/AppImage/appimagetool
> 
> None of these show up with an icon file. Maybe it could be fixed with a more recent (how recent?) version of software, but the point of AppImages is to support applications on any distribution release, so it would be nice to have these working.
> 
> My OS is Gentoo (stable profile desktop) with the newly released stable KDE6 packages.

Try the [zen browser appimage ](https://github.com/zen-browser/desktop/releases/tag/1.0.0-a.37) that one also uses the static runtime (Cemu and Duckstation also use it).

Seems like KDE has issues displaying the appimage icon for appimages that use the static runtime.

**Comment by Samueru-sama** [comment] 2024-09-06 22:00
@sinetek The next appimage release which will happen after this [PR](https://github.com/ivan-hc/Steam-appimage/pull/28) gets merged will make `.DirIcon` an image and not a symlink, maybe this will fix the issue you have.

I have a feeling that the problem is that DirIcon is a symlink and not an appimage and as result KDE has trouble picking up, after reading some comments from an unrelated thing lol.

**Comment by sinetek** [comment] 2024-09-07 19:16
I tried just now, I don't see anything different.

**Comment by Samueru-sama** [comment] 2024-09-07 19:26
> I tried just now, I don't see anything different.

Oh what a shame, if you also don't have the icon with zen-browset, cemu, duckstation and pcsx2 then it is an issue with kde.

**Comment by sinetek** [comment] 2024-09-07 19:39
It is not, the issue also happens on Linux Mint (most popular distribution)

Anyway don’t be discouraged, the project is cool!

**Comment by Samueru-sama** [comment] 2024-09-07 20:49
> It is not, the issue also happens on Linux Mint (most popular distribution) Anyway don’t be discouraged, the project is cool! 

Linux mint using what? If you said linux with using xfce4, I'm assuming that you would have the xapp-thumbnailer already installed and appimages should show the icon: 

![image](https://github.com/user-attachments/assets/18cd9e4e-4b48-4f2a-8292-2dd162647555)

**Comment by ivan-hc** [comment] 2024-09-08 00:37
As I said at start, the AppImage only contain4 files and one symlink (the latter now is a real icon instead, as @Samueru-sama said), so it is impossible that a reliabe thumbnail picker is unable to show the icon.

Also, Thunar file manager handles these in all AppImages that use newer methods to be packaged.

Both me and @Samueru-sama have XFCE/Thunar, but while him uses Arch Linux, I use Debian, so the abovementioned thumbnails plugin is missing in my repositories, so I can't see thumbnails at all.

Maybe is your distro in use that has some libraries or plugins outdated if compared with the new specifics for AppImages? Like me? I don't know. But it is also true that AppImages are not all the same, and if some developers compile them keeping the dependency on the EOL library "libfuse2", we got rid of it. Maybe thumbnails are gone for this, in your case, but as packagers and developers who constantly follow the developments of AppImage as a packaging format, we aim for innovation and compatibility with essential system libraries. Thumbnail management is not something we do. Wile Dolphin, Caya, Tumbnailer... these are the projects that aim to manage files, included in our AppImages.

A thumbnail manager is an extension that must follow our work, since showing icons is its purpose. To handle the thumbnails is something that developers of file managers or their extensions should be able to do, if that is their goal.

That said, I suggest to contact the developers of Dolphin and Caja or of other file managers or of somehow extension... to verify, follow and collect the newer specifics for AppImages. The issue is not of the developers of the AppImages. Sorry.

**Closed by ivan-hc** 2024-09-08 00:37 UTC

**Comment by sinetek** [comment] 2024-09-08 06:00
For the record, it's just your appimages that don't show up with an icon, the others work fine.

**Comment by Samueru-sama** [comment] 2024-09-08 06:02
> For the record, it's just your appimages that don't show up with an icon, the others work fine.

Can you confirm indeed that zen-browser, cemu, etc don't have the same issue? those use the same tooling to make the appimage.

**Comment by sinetek** [comment] 2024-09-08 06:16
> > For the record, it's just your appimages that don't show up with an icon, the others work fine.
> 
> Can you confirm indeed that zen-browser, cemu, etc don't have the same issue? those use the same tooling to make the appimage.

Ah, I guess there's different tools to create these appimages? I give my apologies then, I'll accept the WONTFIX and go do something else.

**Comment by Samueru-sama** [comment] 2024-09-08 06:36
> Ah, I guess there's different tools to create these appimages? The projects you mention also have the same bug. I give my apologies then, I'll accept the WONTFIX and go do something else. 🤷

The issue is that appimages have this well known issue of having a dependency to libfuse2, libfuse2 has been EOL since like 2020. A lot of distros no longer ship libfuse2 by default.

The solution has been for a few years, but only recently it began to be used by default on some tooling, it is called the type2-static runtime, which this project among others use.

However switching the runtime to be static has had it's on set of issues as you can see, most notably it breaks appimagelauncher which is a popular appimage integration tool, and we just learned that it also breaks some appimage thumbnailers as seen here (but not all as you already saw that thunar with the xapp thumbnailer doesn't have the issue).

So you may want to report the issue first at the [runtime](https://github.com/AppImage/type2-runtime) and hopefully it is something stupid that can be fixed, if not then the next step is reporting this to the KDE folks.

And yes there is **a lot** of appimage creation tools, but in this case the issue is likely something with the runtime being static.

**Comment by sinetek** [comment] 2024-09-08 06:45
Can you report the issues? Look, I’m not the one using these tools, I have no idea how your are invoking them or what versions you’re using or how any of this works, except that my icon doesn’t show up.

I don’t use appimagelauncher because it doesnt support OpenRC, but thats another issue.

Also don’t do static runtime on Linux. It just does not work properly and glibc folks don’t support it at all.

**Comment by Azathothas** [comment] 2024-09-14 18:00
The actual issue is that you must have every file that is at the root of the `squashfs-root` have a permission set to `-r-xr-xr-x`
However, yours have a perm like this:
![image](https://github.com/user-attachments/assets/287e7418-8ec8-4b1e-8aae-d2223301996b)

After I changed it to `-r-xr-xr-x`
![image](https://github.com/user-attachments/assets/5fe6ac5c-f5f4-4a78-ad2c-a652a0af41fb)

And remade the appimage:
![image](https://github.com/user-attachments/assets/f87c5a3a-2771-4e92-8cb2-47109b20eeb0)

You can test it yourself: https://pub.ajam.dev/temp/steam_fixed.AppImage
```bash
$ sha256sum steam_fixed.AppImage 
228446454a0c18827f302d2a5fa7cf373dd6e88e64e3a6cf9749f1e81b428034  steam_fixed.AppImage

```

You can get more details and how I discovered this at: https://t.me/VHSgroup/87301/88306

**Comment by Azathothas** [comment] 2024-09-14 22:03
Update: Upon further discussion/deliberation, it's likely that this issue and "fix" may only apply to me.
I discovered this while I was using [nix-appimage](https://github.com/ralismark/nix-appimagel) to create some Appimages.
Apologies if this didn't help at all.

**Comment by sinetek** [comment] 2024-09-17 11:09
> Update: Upon further discussion/deliberation, it's likely that this issue and "fix" may only apply to me. I discovered this while I was using [nix-appimage](https://github.com/ralismark/nix-appimage) to create some Appimages. Apologies if this didn't help at all.

No, this works great as a solution!
I'm guessing it's either the +x on the files that does it, or the packaging with appimagetool that works correctly (I have no idea what the unhelpful ivan-hc guy is using here.

![image](https://github.com/user-attachments/assets/be6eefbc-4cd5-4ab3-9812-e83535d026cb)

**Comment by Azathothas** [comment] 2024-09-17 11:13
@sinetek Thank you for your confirmation.
I tested/verified that this works on about four separate machines (Isolated & freshly booted).
However, the maintainers said that it didn't work on theirs, which is why I thought it was isolated only to me.
Perhaps, their system's configuration differs too much from a general Distro and that's why they disregarded my solution.

**Comment by sinetek** [comment] 2024-09-17 11:21
> @sinetek Thank you for your confirmation. I tested/verified that this works on about four separate machines (Isolated & freshly booted). However, the maintainers said that it didn't work on theirs, which is why I thought it was isolated only to me. Perhaps, their system's configuration differs too much from a general Distro and that's why they disregarded my solution.

I don't need to touch the files, just unpacking and repacking with appimagetool is enough to get the icon back. I tested this with a lot of broken appimages and it always works.

**Comment by Samueru-sama** [comment] 2024-09-17 13:01
>I don't need to touch the files, just unpacking and repacking with appimagetool is enough to get the icon back. I tested this with a lot of broken appimages and it always works.

What appimagetool did you use? 

If it is the appimagetool from [AppImage/AppImageKit](https://github.com/AppImage/AppImageKit) that makes sense, that one is old and still uses the old runtime.

While the appimagetool from [AppImage/appimage](https://github.com/AppImage/appimagetool) or from [probonopd/go-appimage](https://github.com/probonopd/go-appimage) use the static runtime instead.

**Comment by ivan-hc** [comment] 2024-09-17 15:29
@sinetek I repeat, thumbnail managers should adapt to the work of AppImage packagers, not the other way around. I have over 70 AppImages in my repositories, usability is the focus of my workflow. The concern of an AppImage packager is to make the program run on as many systems as possible, regardless of the Desktop Environment and file manager.

File thumbnails are not a priority, and must be managed by dedicated applications or extensions. In @Samueru-sama  case, in XFCE/Thunar on Arch Linux, it worked without these tricks. If what matters most to you are the thumbnails in your files, I think your file manager is wrong at this point.

If what matters to you is how the file looks in the file manager, report the issue to the file manager developers.

> I have no idea what the unhelpful ivan-hc guy is using here.

PS: Do you think they paid me to create these AppImages? There are almost two years of work and research behind this single repository. You say I'm useless, but in the meantime I see that you use my Appimage (or you repackage it using the method shown by @Azathothas , however based on my work), and for free. Think before you shoot out these f**king sentences.

**Comment by sinetek** [comment] 2024-09-18 06:15
> @sinetek I repeat, thumbnail managers should adapt to the work of AppImage packagers, not the other way around. I have over 70 AppImages in my repositories, usability is the focus of my workflow. The concern of an AppImage packager is to make the program run on as many systems as possible, regardless of the Desktop Environment and file manager.

No. There are more than 20 major distributions around, and they do not work on a rolling basis. Meaning an update could be 2+ years away in some cases. Moreover, there are a lot of older (supported) installations, and the point of an AppImage is to offer compatibility to these as well. My angle here is helping newcomers to Linux have a good experience instead of hitting a bumpy road.

> File thumbnails are not a priority, and must be managed by dedicated applications or extensions. In @Samueru-sama case, in XFCE/Thunar on Arch Linux, it worked without these tricks. If what matters most to you are the thumbnails in your files, I think your file manager is wrong at this point.
> 
> If what matters to you is how the file looks in the file manager, report the issue to the file manager developers.
> 
> > I have no idea what the unhelpful ivan-hc guy is using here.
> 
> PS: Do you think they paid me to create these AppImages? There are almost two years of work and research behind this single repository. You say I'm useless, but in the meantime I see that you use my Appimage (or you repackage it using the method shown by @Azathothas , however based on my work), and for free. Think before you shoot out these f**king sentences.

So, an insult. Are you drunk? If users reporting simple bugs cause you to blow a facial vein, maybe the problem is with you? I don't like Arch Linux elitism, it does a lot to drive away new users to the Linux Desktop and it's really a problem for me when this kind of thing happens.

> EDIT: google translate translates "unhelpful" as "useless". It's not that I don't want to help, as I said at the beginning, I have 70 AppImage packages, and like me there are many other packagers who use or not my same packaging methods. Just as the developers of the AppImage file thumbnail manager package for Arch Linux have taken care of the various packaging methods, so should other developers of other extensions, perhaps implementing the same feature in their file managers.
> 
> It's not like the plumber has to rebuild the whole building to fix a broken sink. Do you understand what I mean?

If the artifact only works correctly on rolling-release distributions (there is a reason that's not the standard way of working among the major distributions), then that is a bug.

**Comment by sinetek** [comment] 2024-09-18 06:46
> **Also did this appimage work?**
> 
> https://pub.ajam.dev/temp/steam_fixed.AppImage
> 
> **Don't repackage it with appimagetool or anything like that, does the appimage from that link work out of the box?**

Hi sam,
Unfortunately the icon doesn't show up either with this image.

**Comment by Samueru-sama** [comment] 2024-09-18 16:56
> > **Also did this appimage work?**
> > https://pub.ajam.dev/temp/steam_fixed.AppImage
> > **Don't repackage it with appimagetool or anything like that, does the appimage from that link work out of the box?**
> 
> Hi sam, Unfortunately the icon doesn't show up either with this image.

Yeah, that pretty much confirms that the issue is due to the runtime, [like Ivan said here originally.](https://github.com/ivan-hc/Steam-appimage/issues/27#issuecomment-2332536679)

Worth noting that the xapp-thumbnailer has no problems showing thumbnails for these appimages in both nemo and thunar.

And also after several days of testing @Azathothas managed to get the Steam appimage to show Icon in dolphin, that is the regular Steam appimage and not the "fixed" one, how I don't know lol.

**Comment by Samueru-sama** [comment] 2024-09-18 17:59
Update I managed to get dolphin to show appimage icons.

All I needed to do was install the `libappimage` package.

![image](https://github.com/user-attachments/assets/07dd89b8-a86e-4365-aab0-287932100a3e)

**Comment by ivan-hc** [comment] 2024-09-18 17:59
I'm on Debian Testing, I have installed with `dpkg -i` the following two .deb packages for Linux Mint Elsie (the latest LMDE):
- xapp-appimage-thumbnailer
- xapp-thumbnailers-common

all AppImages I have installed via AM have the thumbnail.

![Istantanea_2024-09-18_19-48-04 png](https://github.com/user-attachments/assets/4a3fe716-dc44-48d7-9b61-c6cf5e7be08e)

and also Steam available here

![Istantanea_2024-09-18_19-48-39](https://github.com/user-attachments/assets/23654f8c-06fe-4e51-9b0a-6635ebb4244c)

you can see the two packages I have installed manually from https://www.debian.org/distrib/packages

and note that libreoffice is an AppImage requiring libfuse2 that I have repackaged the same way I package my AppImages, and the thumbnail works.

also my old Appimage of wine shows the icon

![Istantanea_2024-09-18_19-52-28 png](https://github.com/user-attachments/assets/2d3d253f-4017-49e0-af73-8e4a533432c6)

I downloaded also two Brave and Zen now

![Istantanea_2024-09-18_19-54-11 png](https://github.com/user-attachments/assets/b389ef83-7808-44b6-a39e-ac390ec183cd)

everything works as expected.

So I confirm that xapp-appimage-thumbnailer is a cutting edge thumbnail manager, while Dolphin/KDE/Plasma doesn't give a damn about AppImage as a "dead and unworthy packaging format". This is what happens when most of the Linux community focuses all their efforts on Flatpak, while being fooled by AppImage prejudices.

This is the page of the project https://github.com/linuxmint/xapp-thumbnailers just to give you an idea of ​​what deserves attention.

**Comment by ivan-hc** [comment] 2024-09-18 18:01
> Update I managed to get dolphin to show appimage icons.
> 
> All I needed to do was install the `libappimage` package.

And as Samuel says, libappimage is also needed, I installed libappimage-dev from Debian repositories.

**Comment by philmb3487** [comment] 2024-09-21 15:37
Hello everyone, I found the issue.  libappimage by itself does not support `zstd` compressed images, at least not by default,

`
Squashfs image uses (null) compression, this version supports only xz, zlib.
ERROR: appimage_read_file_into_buffer_following_symlinks : sqfs_open_image error: /home/phil/Applications/Steam-1.0.0.81-2-3-x86_64.appimage
`

The solution is to, 1) activate fusefs support in the libappimage build, and
2) for sys-fs/squashfuse, activate support for zstd.

I think this uses more resources than just using libappimage's default xz compression, since Arch's libappimage goes through fuse, but it works now.

![image](https://github.com/user-attachments/assets/349b11f4-9da1-4a98-b4b7-284128512fba)

**Comment by ivan-hc** [comment] 2024-09-21 16:07
Thanks @philmb3487 you are wellcome, I'll redirect new issues on this thread instead or to your last answer.

I repeat, I have 70 Appimages in numerous repositories, and this seems to be a solution to be implemented in the tools that we packagers download and use daily. Once this is solved, in months and years, it will be useless to continue to have this indication on the README. We just have to wait.

Thank you for the research and the work done. See you next time.
