### ISSUE TITLE
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/Steam-appimage#15] opened 2024-08-05 13:27 UTC
Game: Unravel Two (added as non-Steam game).

Operating System: Gentoo no-multilib (without x32 deps).

Full log:

```
chdir "/home/vitaly/Downloads/Unravel.Two/"
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 8719 for gameID 17314754079368413184
Adding process 8720 for gameID 17314754079368413184
Adding process 8721 for gameID 17314754079368413184
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale C.UTF8...
[error] character map file `UTF8' not found: No such file or directory
pressure-vessel-locale-gen: Generated locale C.UTF8 successfully
setlocale "C.UTF8": No such file or directory
pressure-vessel-locale-gen: Warning: C.UTF8 was generated but does not appear to work!
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[8795]: W: Container startup will be faster if missing locales are created at OS level
Adding process 9074 for gameID 17314754079368413184
Uploaded AppInterfaceStats to Steam
Removing process 9074 for gameID 17314754079368413184
Removing process 8721 for gameID 17314754079368413184
Removing process 8720 for gameID 17314754079368413184
Removing process 8719 for gameID 17314754079368413184
```

**Comment by ivan-hc** [comment] 2024-08-05 15:06
I don't know how Steam works with external programs, may it be an anticheat issue?

Have you tried to use the one from https://store.steampowered.com/app/1225570/Unravel_Two/ ?

**Comment by Samueru-sama** [comment] 2024-08-05 18:40
Those locale errors might be what's causing the issue. 

Test with this appimage and let me know if it fixes the issue: https://github.com/Samueru-sama/Steam-appimage/releases/tag/continuous

**Comment by vitaly-zdanevich** [comment] 2024-08-05 22:05
Thanks, tried AppImage from the link - still do not run :(

```
chdir "/home/vitaly/Downloads/Unravel.Two/"
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 28147 for gameID 17314754079368413184
Adding process 28148 for gameID 17314754079368413184
Adding process 28149 for gameID 17314754079368413184
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale C.UTF8...
[error] character map file `UTF8' not found: No such file or directory
pressure-vessel-locale-gen: Generated locale C.UTF8 successfully
setlocale "C.UTF8": No such file or directory
pressure-vessel-locale-gen: Warning: C.UTF8 was generated but does not appear to work!
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[28224]: W: Container startup will be faster if missing locales are created at OS level
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Adding process 28504 for gameID 17314754079368413184
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
fsync: up and running.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Adding process 28505 for gameID 17314754079368413184
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Adding process 28506 for gameID 17314754079368413184
Adding process 28507 for gameID 17314754079368413184
Adding process 28510 for gameID 17314754079368413184
Adding process 28512 for gameID 17314754079368413184
Adding process 28515 for gameID 17314754079368413184
Adding process 28525 for gameID 17314754079368413184
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Adding process 28538 for gameID 17314754079368413184
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Adding process 28544 for gameID 17314754079368413184
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Adding process 28572 for gameID 17314754079368413184
[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
ERROR: ld.so: object 'sdl_block_screensaver_inhibit.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Adding process 28590 for gameID 17314754079368413184
pid 28508 != 28507, skipping destruction (fork without exec?)
[2024-08-06 02:04:47] Background update loop checking for update. . .
[2024-08-06 02:04:47] Checking for available updates...
[2024-08-06 02:04:47] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=3396091871
[2024-08-06 02:04:47] Manifest download: send request
Uploaded AppInterfaceStats to Steam
Removing process 28590 for gameID 17314754079368413184
Removing process 28572 for gameID 17314754079368413184
Removing process 28544 for gameID 17314754079368413184
Removing process 28538 for gameID 17314754079368413184
Removing process 28525 for gameID 17314754079368413184
Removing process 28515 for gameID 17314754079368413184
Removing process 28512 for gameID 17314754079368413184
Removing process 28510 for gameID 17314754079368413184
Removing process 28507 for gameID 17314754079368413184
Removing process 28506 for gameID 17314754079368413184
Removing process 28505 for gameID 17314754079368413184
Removing process 28504 for gameID 17314754079368413184
Removing process 28149 for gameID 17314754079368413184
Removing process 28148 for gameID 17314754079368413184
Removing process 28147 for gameID 17314754079368413184
[2024-08-06 02:04:48] Manifest download: waiting for download to finish
[2024-08-06 02:04:49] Manifest download: finished
[2024-08-06 02:04:49] Download skipped: /steam_client_ubuntu12?t=3396091871 version 1721173382, installed version 1721173382, existing pending version 0
[2024-08-06 02:04:49] Nothing to do
```

**Comment by ivan-hc** [comment] 2024-08-05 22:09
@vitaly-zdanevich @Samueru-sama I've found someone with the same error https://forum.manjaro.org/t/cannot-run-steam-ld-preload-cannot-be-preloaded/140902

**Comment by vitaly-zdanevich** [comment] 2024-08-05 22:12
From that link I see

> Looks like you are trying to run a 32-bit game, while Manjaro is 64-bit. You normally should have the required 32-bit libraries installed

I have Gentoo no-multilib - without 32 libraries. This is why I was looking to Steam in AppImage - to have dependencies inside.

**Comment by ivan-hc** [comment] 2024-08-05 22:13
@Samueru-sama it seems that we forgot to add lib32-glib

also the AUR package lib32-glibc-eac-bin says that the latter is required by lib32-glib

https://aur.archlinux.org/packages/lib32-glibc-eac-bin?all_reqs=1#pkgreqs

**Comment by ivan-hc** [comment] 2024-08-05 22:35
I have just added the missing package lib32-glibc, from about 12 minutes it should be ready, you can also update it from "AM" if you have installed it from there

but again, wait at least 11 minutes

**Comment by Samueru-sama** [comment] 2024-08-05 22:37
[The LD_PRELOAD errors are caused by the screensaver fix and are normal](https://github.com/Samueru-sama/fixsteam/issues/1)

>it seems that we forgot to add lib32-glib

There isn't a `lib32-glib` anymore on arch, the package is instead `lib32-glib2` and it is already in appimage.

--------------------------------------------------

@vitaly-zdanevich I think you have to test the issue with native steam, proton isn't perfect running every single windows executable. 

>I have just added the missing package lib32-glibc, from about 12 minutes it should be ready, you can also update it from "AM" if you have installed it from there

that will break the anti-cheat, lib32-glibc conflicts with lib32-eac-glibc.

**Comment by ivan-hc** [comment] 2024-08-05 22:39
> There isn't a `lib32-glib` anymore on arch, the package is instead `lib32-glib2` and it is already in appimage.

![Istantanea_2024-08-06_00-38-13](https://github.com/user-attachments/assets/8e920990-efd7-4c5d-afc4-bb25c169b868)

**Comment by ivan-hc** [comment] 2024-08-05 22:42
@vitaly-zdanevich OK, forgot what I said before, the next release is suspended

**Comment by ivan-hc** [comment] 2024-08-05 22:43
also I need to change glasses

> > There isn't a `lib32-glib` anymore on arch, the package is instead `lib32-glib2` and it is already in appimage.
> 
> ![Istantanea_2024-08-06_00-38-13](https://private-user-images.githubusercontent.com/88724353/355257056-8e920990-efd7-4c5d-afc4-bb25c169b868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4OTc4NjMsIm5iZiI6MTcyMjg5NzU2MywicGF0aCI6Ii84ODcyNDM1My8zNTUyNTcwNTYtOGU5MjA5OTAtZWZkNy00YzVkLWFmYzQtYmIyNWMxNjliODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDIyMzkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMjFjODcyZGRkNmIyN2EwNjUzYTVkODdmODZiZGY1MTkwZWRkMTBhNTM2NTgwZTI1NzYzYjcyMThkY2YxNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.awvG6ZDk2AwWQjVK_eF9o7TVR92S6e61Gssq-5EmKG4)

I've not noticed that one ends with 2 and another with c

**Comment by vitaly-zdanevich** [comment] 2024-08-06 00:53
> you have to test the issue with native steam, proton isn't perfect running every single windows executable.

https://www.protondb.com/app/1225570
![image](https://github.com/user-attachments/assets/35ae3ca8-18e7-4453-9a85-b1c10fe71ab4)

**Comment by Samueru-sama** [comment] 2024-08-06 01:02
That isn't testing, for example BeamNG is rated gold in protondb but it has had several breaking issues before. And also protondb assumes that you are using the game thru steam and not externally like you just did. 

If I had the game I would test it.

>I do not know how to correctly install x32 liraries on Gentoo no-multilib :(

You could always install distrobox and launch an arch or arch fork container and install steam that way. 

To enable the 32bit repo on arch it is as simple as editing `/etc/pacman.conf` and removing the `#` from the line that says `[multilib]` and the line right below that one.

**Comment by ivan-hc** [comment] 2024-08-06 01:05
@vitaly-zdanevich Be wary of ratings, especially if you are running a game differently than Steam expects.

**Comment by Samueru-sama** [comment] 2024-08-06 01:19
@vitaly-zdanevich Have you tried using bottles instead to launch the game?

I read a bit and it seems that game needs Origin to be running, that's a nightmare, I used to play battlefield before moving to windows and stopped doing so because of that.

**Comment by vitaly-zdanevich** [comment] 2024-08-06 03:02
Wow, thanks, in Bottle I installed, but yeah Origin..... 
![image](https://github.com/user-attachments/assets/169907b8-6f39-467f-a0c3-cb65834c0067)

**Comment by vitaly-zdanevich** [comment] 2024-08-06 03:20
Hm in Bottles I cannot start command like, in logs I see:

> 07:20:24 (WARNING) Terminal not supported.

**Comment by ivan-hc** [comment] 2024-08-06 03:30
> Hm in Bottles I cannot start command like, in logs I see:
> 
> > 07:20:24 (WARNING) Terminal not supported.

???

![Istantanea_2024-08-06_05-29-47](https://github.com/user-attachments/assets/7cd5b82a-6503-402a-8c46-88260227f8af)

**Comment by vitaly-zdanevich** [comment] 2024-08-06 03:40
But from GUI it is not starting a terminal.

**Comment by ivan-hc** [comment] 2024-08-06 03:41
I'll include xterm then

**Comment by ivan-hc** [comment] 2024-08-06 03:45
wait at least 10 minutes before you download Bottles again from https://github.com/ivan-hc/Bottles-appimage/releases/tag/continuous

just started a workblow to rebuild it https://github.com/ivan-hc/Bottles-appimage/actions/runs/10259910328/job/28385093983

**Comment by ivan-hc** [comment] 2024-08-06 03:52
try now

**Comment by vitaly-zdanevich** [comment] 2024-08-06 05:16
Started, thanks, but white... What do you think about more eye-safe-night color?

![image](https://github.com/user-attachments/assets/161f9b8c-1f14-42ea-a057-cb6c379685cc)

**Comment by ivan-hc** [comment] 2024-08-06 12:04
it is xterm, add a .Xdefaults file in your hme with this content
```
xterm*background: black
xterm*foreground: white
```
and logout/login

**Comment by ivan-hc** [comment] 2024-08-12 16:12
@vitaly-zdanevich have you solved

**Comment by vitaly-zdanevich** [comment] 2024-08-12 23:59
Unravel Two no :(

**Comment by vitaly-zdanevich** [comment] 2024-08-13 00:01
I can run the trial with such error, but not the game :(
![image](https://github.com/user-attachments/assets/1bda3411-ffeb-4c7e-9c6d-fd023dec1537)

Tried different Proton versions.

**Comment by ivan-hc** [comment] 2024-08-13 00:05
Bottles?

Have you tried to play with the options? Maybe there is an anticheat issue. I don't know.

**Comment by vitaly-zdanevich** [comment] 2024-08-14 10:12
I tried Bottles too.

What options?

**Comment by ivan-hc** [comment] 2024-08-14 13:56
in the Settings tab of your bottle, surelly there is something gone wrong with your installation

also, take a look to somehow forum if others have the same issue with the same game, on Bottles or WINE in general

I also had issues like this in FIFA games from EA, but was for the offline patch not installed (a CD was required, but my game is 20 years old).

**Comment by ivan-hc** [comment] 2024-09-05 19:55
I close this issue for inactivity

**Closed by ivan-hc** 2024-09-05 19:55 UTC
